spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  profiles:  # 로그
    active: dev  # 기본 프로파일 (dev, test, prod 중 선택)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/my_shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    name: my_shop

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:                    # ( TRACE < DEBUG < INFO < WARN < ERROR )
    root: INFO              # 기본 값은 INFO 지정,
    com.jihun.myshop: WARN  # 설정한 패키지 이하에서 발생하는 로그는 단계 이상의 로그만 출력

server:
  port: 8081
